spring.datasource.url=jdbc:postgresql://localhost:15432/leap_projectdb
spring.datasource.username=postgres
spring.datasource.password=neued4!
server.port=8081

# MyBatis Configuration - using inline annotations
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.use-generated-keys=true
mybatis.configuration.default-executor-type=SIMPLE

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ribbittrade@gmail.com
spring.mail.password=iscs sssr ozrl yrpq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.default-encoding=UTF-8